spring.application.name=JavaLab
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/binance?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=sa



spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=SpringBootHikariCP

spring.batch.jdbc.initialize-schema=always


logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.activemq.broker-url=tcp://91-ITB-105808:61616/?jms.redeliveryPolicy.maximumRedeliveries=1
spring.activemq.username=admin
spring.activemq.password=admin

springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.show-actuator=true