spring.application.name=JavaLab


server.port=9090

springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.api-docs.enabled=true